baseURL = "http://helencook.art/"
languageCode = "en-us"
title = "Helen Cook"
theme = ["hugo-cloak-email", "hcatheme"]
assetDir = "assets"
summaryLength = 40

[Params]
    logo = "logo.png"
    banner = "banner.jpg"
    banneralt = "green to yellow watercolour gradient"
    # params for links in the menu
    email = "helen.cook@gmail.com"
    emailsubject = "Mail from HelenCook.art"
    instagramlink = "http://instagram.com/helencook"
    instagramhandle = "@helencook"
    etsy = "http://etsy.com/uk/shop/HelenCookArt"

[taxonomies]
  gallery="galleries"
  medium="media"

[menu]
  [[menu.main]]
    identifier="home"
    name="Home"
    url="/"
    pre="<i class=\"fa fa-fw fa-home\"></i>"
    weight=1
  [[menu.main]]
    identifier="artwork"
    name="Artwork"
    url="/artwork"
    pre="<i class=\"fa fa-fw fa-brush\"></i>"
    weight=2
  [[menu.main]]
    name="Transparency"
    url="/artwork/transparency"
    weight=1
    parent="artwork"
  [[menu.main]]
    name="Mushrooms"
    url="/artwork/mushrooms"
    weight=2
    parent="artwork"
  [[menu.main]]
    name="Paintings"
    url="/artwork/standalone-works"
    weight=3
    parent="artwork"
#  [[menu.main]]
#    name="Artist Books"
#    url="/artwork/books"
#    weight=4
#    parent="artwork"
# [[menu.main]]
#   name="Pigments"
#   url="/pigments"
#   pre="<i class=\"fa fa-fw fa-palette\"></i>"
#   weight=3
 [[menu.main]]
   name="Apps"
   url="/apps"
   pre="<i class=\"fa fa-fw fa-gear\"></i>"
   weight=4
  [[menu.main]]
    name="Updates"
    url="/blog"
    pre="<i class=\"fa fa-fw fa-pen-nib\"></i>"
    weight=5
  [[menu.main]]
    name="About"
    url="/about"
    pre="<i class=\"fa fa-fw fa-eye\"></i>"
    weight=6
  [[menu.main]]
    name="Contact"
    url="/contact"
    pre="<i class=\"fa fa-fw fa-circle-question\"></i>"
    weight=7
