baseURL = "http://helencook.art/"
languageCode = "en-us"
title = "Helen Cook"
theme = "hcatheme"
assetDir = "assets"
summaryLength = 40

[Params]
    logo = "logo.png"
    banner = "banner.jpg"
    banneralt = "green to yellow watercolour gradient"
    # params for links in the menu
    email = "helen.cook@gmail.com"
    emailsubject = "Mail from HelenCook.art"
    instagramlink = "http://instagram.com/helencook"
    instagramhandle = "@helencook"
    etsy = "http://etsy.com/uk/shop/HelenCookArt"

[taxonomies]
  gallery="galleries"
  medium="media"

[menu]
  [[menu.main]]
    identifier="artwork"
    name="Artwork"
    url="/artwork"
    weight=2
  [[menu.main]]
    name="Transparency"
    url="/artwork/transparency"
    weight=1
    parent="artwork"
  [[menu.main]]
    name="Mushrooms"
    url="/artwork/mushrooms"
    weight=2
    parent="artwork"
  [[menu.main]]
    name="Standalone works"
    url="/artwork/standalone-works"
    weight=3
    parent="artwork"
#  [[menu.main]]
#    name="Artist Books"
#    url="/artwork/books"
#    weight=4
#    parent="artwork"
# [[menu.main]]
#   name="Pigments"
#   url="/pigments"
#   weight=3
# [[menu.main]]
#   name="Apps"
#   url="/apps"
#   weight=4
  [[menu.main]]
    name="Updates"
    url="/blog"
    weight=5
  [[menu.main]]
    name="About"
    url="/about"
    weight=6
  [[menu.main]]
    name="Contact"
    url="/contact"
    weight=7
